/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaAdministracionPaquetes;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;

/**
 *
 * @author allanvz
 */
public class VentanaAtender extends javax.swing.JFrame {

    DefaultListModel listModel;
    
    /**
     * Creates new form VentanaAtender
     */
    public VentanaAtender() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.listModel = new DefaultListModel();
        this.listAtender.setModel(listModel);
    }
    
    public void atender(String element) {
        this.listModel.addElement(element);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listAtender = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 23));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        listAtender.setMinimumSize(new java.awt.Dimension(400, 0));
        jScrollPane1.setViewportView(listAtender);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listAtender;
    // End of variables declaration//GEN-END:variables
}
